### ISSUE TITLE
Manga episode

### ISSUE THREAD

**Issue by arnauddorgans** [thcolin/oleoo#11]
Merci pour ta lib :) 
J'ai remarqué que les episodes de manga de semblent pas etre lu correctement:

{ original:
   'Dragon.Ball.Super.E89.FRENCH.1080P.HDTV.x264-R342 [ www.Torrent9.PH ].mkv',
  language: 'FRENCH',
  source: 'HDTV',
  encoding: 'x264',
  resolution: '1080p',
  dub: null,
  year: null,
  flags: null,
  season: null,
  episode: null,
  episodes: [],
  type: 'movie',
  group: 'R342',
  title: 'Dragon Ball Super E89',
  generated: 'Dragon.Ball.Super.E89.FRENCH.1080p.HDTV.x264-R342',
  score: 5 }

**Comment by thcolin** [comment]
Ah yes, merci, j'y avais pas pensé ! J'ai push un fix #12, maintenant la lib gère les release avec un (ou plusieurs épisodes) et aucune saison comme les mangas.
