### ISSUE TITLE
[Request] Top team

### ISSUE THREAD

**Issue by arnauddorgans** [thcolin/oleoo#13]
Je pense a un algo d'auto remove de [xxx] si premier char

{ original:
   '[ www.Torrent9.PH ] The.Darkest.Minds.2018.MULTi.1080p.WEB-DL.DD5.1.H264-ACOOL.mkv',
  language: 'MULTI',
  source: 'WEB-DL',
  encoding: 'h264',
  resolution: '1080p',
  dub: null,
  year: '2018',
  flags: [ 'DD5.1' ],
  season: null,
  episode: null,
  episodes: [],
  type: 'movie',
  group: 'ACOOL.mkv',
  title: ' Www Torrent9 Ph The Darkest Minds',
  generated:
   'Www.Torrent9.Ph.The.Darkest.Minds.2018.MULTI.1080p.WEB-DL.h264.DD5.1-ACOOL.mkv',
  score: 7 }

**Comment by thcolin** [comment]
J'ai ajouté une option pour supprimer des chaines de caractères en fonction d'expressions, j'ai aussi ajouté des valeurs par défaut (dont torrent9) dans le fichier [rules.json](https://github.com/thcolin/oleoo/blob/master/src/rules.json), voir 4cdb8ce4dc6aa1909d2eee21076018bc080bc4db
