### ISSUE TITLE
Chinese

### ISSUE THREAD

**Issue by kkm** [thcolin/oleoo#23]
My.Best.Friends.Breakfast.2022.CHINESE.1080p.BluRay.x265-VXT
Recognized as VO

**Comment by kkm** [comment]
https://github.com/thcolin/oleoo/blob/1e2723519317bb79c40c7460a99a4637bfa98bea/src/rules.json#L175

**Comment by thcolin** [comment]
Should be solved with `oleoo@1.1.1`
