### ISSUE TITLE
Issue with TV Show Title Detection When 'FW' is Present in File Name

### ISSUE THREAD

**Issue by imike57** [thcolin/oleoo#24]
Hi!

I just wanted to report an issue regarding a TV show title pattern.

When using the pattern:

`Run.the.World.S02E07.FRENCH.1080p.WEB.H264-FW-WEBSITE`

It returns "Run the" as the title, which seems to be incorrect.

However, when the "FW" part is removed, as in:

`Run.the.World.S02E07.FRENCH.1080p.WEB.H264-WEBSITE`

It correctly returns "Run the World."

**Comment by thcolin** [comment]
Should be solved with `oleoo@1.1.1`
