### ISSUE TITLE
Roman letters (I-III) issue with danish content

### ISSUE THREAD

**Issue by dezza** [thcolin/oleoo#29]
Hey friend, I notice your idea behind:
https://github.com/thcolin/oleoo/blob/90aaf51346486c8f45d5d8121d2b0069a34d54f3/src/index.js#L212-L212

Roman letters in movie series numbering, I assume.

In danish "I" means "in" so its very common in names.

Examples:

```
Nattevagten.Daemoner.gaar.i.arv.2023
```
would be
```
Nattevagten Daemoner Gaar 1 Arv
```
Which means the title is mangled, since it means "in" not numbering of movie series.

Is it safe to assume roman letters for movie series numbering would be at the end of a title? (*Movie.Part.II, Phantom.Menace.Episode.I, etc*)

.. Cuz that would eliminate this issue.

```js
  let yearPos = 0
  words.reduceRight((_, w, i) => {
    if (/19|20\d{2}/.test(w)) {
      yearPos = i
    }
  }, null)

  release.title = waste
    .replace(/[\.\-]+/, '.')
    .split('.')
    .filter((word, position) => word === words[position])
    .map((word, i) => {
      if (word.split('').every(char => ['i', 'I'].includes(char)) && i === (yearPos - 1)) {
        return word.length
      } else {
        return word
      }
    })
```

Would this work for you? Checks if its exactly before year-tag and then applies.

**Comment by thcolin** [comment]
Should be solved with `oleoo@1.1.1`
